#!/bin/bash


function auto_install {
	sudo ubuntu-drivers autoinstall
}

function ubuntu_drivers_devices {
	sudo ubuntu-drivers devices 
}


function add_gprahics_ppa {
	sudo add-apt-repository ppa:graphics-drivers/ppa
	sudo apt update -y -qq
}


function nvidia_430 {
	sudo apt install nvidia-driver-430

}

function nvidia_418 {
	sudo apt install nvidia-driver-418
}

function nvidia_390 {
	sudo apt install nvidia-driver-390
}

function nvidia_384 {
	sudo apt install nvidia-384
}



function install_drivers {
	# install
	echo_message title "Starting Driver installation..."
	# Draw window
	UPDATE=$(eval `resize` && whiptail \
		--notags \
		--title "Install $NAME" \
		--menu "\nWhat ${NAME,,} would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'auto_install'    	'Auto Install Drivers' \
		'ubuntu_drivers_devices' 'ubuntu_drivers_devices' \
		'add_gprahics_ppa'      'Add Grpahics PPA' \
		'nvidia_430'   		'Install nvidia_430' \
		'nvidia_418'   		'Install nvidia_418' \
		'nvidia_390'   		'Install nvidia_390' \
		'nvidia_384'   		'Install nvidia_384' \
		3>&1 1>&2 2>&3)

	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$UPDATE' function..."
		$UPDATE
	else
		# Cancelled
		echo_message info "Drivers installation cancelled."
		main
	fi
}
