#!/bin/bash


function install_vscode { 
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor  | sudo apt-key add -
	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
	sudo apt-get update
	sudo apt-get install code
}
